name: Taylor Dixson
favicon: null
layout_spectrum: 0.74486
typography_spectrum: 0.64619
title: F-crazy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#313f40'
    - '#070604'
    - '#88806b'
    - '#c8a98a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
