name: Photo Gear
favicon: null
layout_spectrum: 0.38403
typography_spectrum: 0.64619
title: F/Crazy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070705'
    - '#45605b'
    - '#d7dbda'
    - '#96846c'
    - '#c5b38f'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
