name: Photo Gear
favicon: null
layout_spectrum: 0.39796
typography_spectrum: 0.64619
title: F/Crazy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070705'
    - '#45605b'
    - '#d7dbda'
    - '#96846c'
    - '#c5b38f'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
