name: Taylor Dixson
favicon: null
layout_spectrum: 0.49558
typography_spectrum: 0.64619
title: F-crazy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f8fb'
    - '#c5c4ca'
    - '#002653'
    - '#75685f'
    - '#418dd9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
