name: Taylor Dixson
favicon: null
layout_spectrum: 0.50717
typography_spectrum: 0.64619
title: F-crazy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#031f2d'
    - '#224f64'
    - '#febb77'
    - '#b8765e'
    - '#ad0648'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
